apiVersion: v1
kind: Service
metadata:
  name: posts-srv
spec:
  type: NodePort
  selector:
    app: posts
  ports:
    - name: posts
      port: 4000 #We are creating a node port service.The node port service is going to have a port of its own. So that is referred to as simply the port.
      targetPort: 4000  #This is the actual port that our application is listing for traffic on.
#The port and the target port do not have to be identical.

#So this could be post: 5000 right here.

#And if we make a request to port 5000 on the node port service, the service will redirect that traffic

#to port 4000 on the container.