apiVersion: apps/v1
kind: Deployment
metadata:
  name: query-depl
spec:
  replicas: 1 #Replicas is the number of pods that we want to create running some particular image.
  selector: #This selector right here is saying, take a look at all the different pods that have been created.Find all the pods with a label of app posts.
    matchLabels:
      app: query
  template: #the template is where we specify the exact configuration of a pod that we want this deployment to create.
    metadata:
      labels: #We are saying that we want the pod to have a label of app posts.
        app: query
    spec:
      containers:
        - name: query
          image: hridoy123/query
          imagePullPolicy: Never
--- 
# To create multiple objects inside of a single YAML file.We add on dash, dash, dash, and then just go down to the next line.
apiVersion: v1
kind: Service
metadata:
  name: query-srv
spec:
  selector:
    app: query
  type: ClusterIP
  ports:
    - name: query
      protocol: TCP
      port: 4002
      targetPort: 4002


  
#But to be honest with you, a deployment kind of has a hard time figuring out which pods it should manage

#inside of our cluster.

#In other words, if a set of pods get created, we have to somehow give the deployment some information

#and tell it, Hey, these pods over here.

#These are the ones you need to manage.

#And that's what the goal of this selector and metadata labels app thing is all about.